name = "aselviptur-api"
main = "api/worker.js"
compatibility_date = "2026-08-08"

workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "aselviptur-production"
database_id = "03e532d7-0f2d-4016-917a-62e73b657829"
